name: CI/CD Workflow

on:
  push:
    branches:    
      - 'v**' # matches v1.0, v2.3, etc.
    # Exclude commits with #NORUN
    if: "!contains(github.event.head_commit.message, '#NORUN')" 

jobs:

  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Run Trivy scan
      uses: aquasecurity/trivy-action@master
      with: 
        scan-type: 'fs'
        format: 'table'
        output: 'trivy-results.txt'
        severity: 'CRITICAL'
        
    - name: Upload Trivy results to Slack
      if: failure()
      uses: slackapi/slack-github-action@v1.23.0
      with:
        slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_TOKEN }} 
        channel-id: ${{ secrets.SLACK_CHANNEL }}
        filename: trivy-results.txt

  build:
    needs: scan
    if: success() 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        image-name: my-docker-hub-id/go-fortune
        image-tag: ${{ github.sha }}
        push: true
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} 
        
    - name: Sign Docker image
      uses: sigstore/cosign-installer@main

    - name: Slack success notification
      uses: slackapi/slack-github-action@v1.23.0
      with:
        slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_TOKEN }}
        channel-id: ${{ secrets.SLACK_CHANNEL }}
        text: |
          Success! 
          Name: <your name>
          Matric: <matric number>
          Email: <email> 
          Repo: ${{ github.repository }}
          Docker: <Docker Hub URL>