name: CI/CD Workflow

on:
  push:
    branches:    
      - 'v[0-9].[0-9]' # matches v1.0, v2.3, etc.


jobs:

  scan_send_build:
    # Only run this job if the commit message does not start with '#NORUN'
    if:  ${{ !startsWith(github.event.head_commit.message, '#NORUN') }}

    runs-on: ubuntu-latest
    steps:
    - name: Checkout code in scan job
      uses: actions/checkout@v4

      
    - name: Run Trivy scan
      uses: aquasecurity/trivy-action@master
      id: trivy
      continue-on-error: true # Continue on error, the outcome will be failure
      with: 
        scan-type: 'fs'
        format: 'table'
        output: 'trivy-results.txt'
        exit-code: '1' # Will fail the *job* if there are any CRITICAL or HIGH vulnerabilities
        severity: 'CRITICAL,HIGH' # CRITICAL will Success, High will Fail 
    
        
    

    #if scan fail, then send slack notification

    - name: send scan failed notification to slack
      if:  ${{ steps.trivy.outcome == 'failure' }}
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          {
            "blocks": [
              {
                "type": "context",
                "elements": [
                  {
                    "type": "image",
                    "image_url": "https://github.com/${{ env.github_actor_me }}.png?size=16",
                    "alt_text": "avatar"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "<https://github.com/${{ env.github_actor_me }}|chenyu01>"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Ref:*\n${{ github.ref }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Event:*\n${{ github.event_name }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Actions URL:*\n <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Build and Push>"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Commit:*\n <https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha}}>"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Scan failed: - ${{ secrets.NAME }}*\nFailed trivy scan, see uploaded report"
                  }
                ]
              },
              {
                "type": "divider"
              }

            ]
          }

        
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
    

      


