name: cosign test

on:
  push:
    branches: v1.0 #trigger on push to v1.0 branch


jobs:
    build-image:
      runs-on: ubuntu-latest
  
      permissions:
        contents: read
        packages: write
        id-token: write # needed for signing the images with GitHub OIDC Token
  
      name: build-image
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 1
  
        - name: Install Cosign
          uses: sigstore/cosign-installer@v3.1.1
        
        - run: |
            echo "${{ secrets.COSIGN_PRIVATE_KEY }}" > cosign.key
            cat cosign.key

        - name: Sign image with a key
          run: |
            cosign sign --yes --key cosign.key "${TAGS}@${DIGEST}" 
          env:
            TAGS: ${{ secrets.DOCKER_USERNAME }}/cicd:test
            COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
            COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
            DIGEST: sha256:1b787ef046054a13dac3c1366f3e04cc8bde0fa7702607ba57592e39f623c472?uuid=25257F26-80B6-40D7-A986-2C4F0B54243D
  
