name: Version Branch Workflow

on: 
  push:
    branches:    
      - 'v[0-9].[0-9]'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Scan the branch
        run: |
          trivy fs -s HIGH .